[build-system]
requires = ["setuptools>=61", "wheel", "cmake"]
build-backend = "setuptools.build_meta"

[project]
name = "maidenhead"
version = "1.0.0rc2"
description = "A Python library for working with Maidenhead grid squares, geographic locators used mainly in Amateur Radio."
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Ben Owen (2E0XPQ)" }]
classifiers = [
  "Programming Language :: Python :: 3",
]
urls = { "Repository" = "https://github.com/DorjeStego/Maidenhead" }
dependencies = ["orjson"]

[project.optional-dependencies]
geo = ["geographiclib"]

[project.scripts]
mh = "maidenhead.cli_native:main"
mh_cli = "maidenhead.cli_native:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
maidenhead = ["py.typed", "bin/mh_cli*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
